export const CART_ACTION_TYPES = {
    SHOW_HEADER: 'SHOW_HEADER',
    APP_IS_LOADING: 'APP_IS_LOADING',
    SET_TOKEN: 'SET_TOKEN',
    SET_MENUS: 'SET_MENUS',
    SET_CATEGORIES: 'SET_CATEGORIES',
    SET_PRODUCTS: 'SET_PRODUCTS',
} as const